name: Sync GitHub Secrets to Vault (Self-Hosted)

on:
  push:
    paths:
      - qa_pass # Trigger only when files in the 'qa' directory are modified
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-secrets:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Secrets to Vault
        run: |
          export VAULT_ADDR="http://127.0.0.1:8200"
          export VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}"

          vault status

          # Read the preprod file and write keys to Vault
          while IFS= read -r line || [[ -n "$line" ]]; do
            # Split the line into key and value
            IFS='=' read -r key value <<< "$line"

            # Skip empty lines or comments
            [[ -z "$key" || "$key" == \#* ]] && continue

            # Push the key-value pair to Vault
            vault kv put "preprod/config" "$key"="$value"
          done < ./qa/preprod
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
