name: Sync GitHub Secrets to Vault (Self-Hosted)

on:
  push:
    paths:
      - qa # Trigger only when the 'qa' file is modified
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-secrets:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Secrets to Vault
        run: |
          export VAULT_ADDR="http://127.0.0.1:8200"
          export VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}"

          vault status

          # Read the qa file and replace placeholders with GitHub secrets
          while IFS= read -r line || [[ -n "$line" ]]; do
            # Skip empty lines or comments
            [[ -z "$line" || "$line" == \#* ]] && continue

            # Extract the key and value
            IFS='=' read -r key value <<< "$line"

            # Replace placeholder with the actual GitHub secret
            value=${value//\$\{\{ secrets./}
            value=${value// \}\}/}

            # Use the actual secret value
            actual_value="${{ secrets.${value} }}"

            # Push the key-value pair to Vault
            vault kv put preprod/config "$key"="$actual_value"
          done < ./qa
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
