name: Sync GitHub Secrets to Vault (Self-Hosted)

on:
  push:
    paths:
      - qa # Trigger only when the 'qa' file is modified
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-secrets:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Secrets to Vault
        run: |
          export VAULT_ADDR="http://127.0.0.1:8200"
          export VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}"

          vault status

          # Define a lookup table for GitHub secrets
          declare -A secrets
          secrets=(
            ["MY_SECRET_1"]="${{ secrets.MY_SECRET_1 }}"
            ["MY_SECRET_2"]="${{ secrets.MY_SECRET_2 }}"
          )

          # Read the qa file and use the lookup table to resolve secrets
          while IFS= read -r line || [[ -n "$line" ]]; do
            # Skip empty lines or comments
            [[ -z "$line" || "$line" == \#* ]] && continue

            # Extract the key
            IFS='=' read -r key placeholder <<< "$line"

            # Resolve the secret value using the lookup table
            value="${secrets[$key]}"

            # Push the key-value pair to Vault
            vault kv put preprod/config "$key"="$value"
          done < ./qa
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
