name: Sync GitHub Secrets to Vault (Self-Hosted)

on:
  push:
    paths:
      - preprod
  workflow_dispatch:

jobs:
  sync-secrets:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Secrets with Vault
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          MY_SECRET1: ${{ secrets.MY_SECRET1 }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          MY_SECRET3: ${{ secrets.MY_SECRET3 }}
        run: |
          export VAULT_ADDR="http://127.0.0.1:8200"

          # Check required commands
          command -v jq >/dev/null 2>&1 || { echo "jq is required but not installed. Exiting."; exit 1; }
          command -v vault >/dev/null 2>&1 || { echo "Vault CLI is required but not installed. Exiting."; exit 1; }

          vault status

          # Fetch existing Vault configurations
          existing_configs=$(vault kv list -format=json preprod | jq -r '.[]')

          # Read the preprod file
          desired_configs=()
          while IFS= read -r line || [[ -n "$line" ]]; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            IFS='=' read -r config params <<< "$line"

            # Replace placeholders with secrets
            params=$(echo "$params" | sed "s|{{MY_SECRET1}}|$MY_SECRET1|g" | sed "s|{{MY_SECRET2}}|$MY_SECRET2|g" | sed "s|{{MY_SECRET3}}|$MY_SECRET3|g")

            desired_configs+=("$config")

            # Add or update configuration
            echo "Processing $config with parameters: $params"
            vault kv put "preprod/$config" $params || { echo "Failed to update $config in Vault. Skipping."; continue; }
          done < ./preprod

          # Remove missing configurations
          for existing in $existing_configs; do
            if [[ ! " ${desired_configs[@]} " =~ " ${existing} " ]]; then
              echo "Removing $existing from Vault..."
              vault kv delete "preprod/$existing" || { echo "Failed to remove $existing. Skipping."; continue; }
            fi
          done
