name: Overwrite Local File

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Overwrite Local File
        run: |
          cp ./test.txt /home/test.txt
          echo "File /home/test.txt has been updated from GitHub."
