name: Execute Script to Write Secret

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  write-file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x ./write_secret.sh

      - name: Execute Script
        run: ./write_secret.sh
