name: Overwrite Local File with Secret

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Overwrite Local File with Secret
        run: |
          echo "${{ secrets.MY_SECRET }}" > /home/test.txt
        shell: bash
