name: Replace Placeholders with Secrets interm

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug File Location
        run: |
          echo "Listing all files in the repository..."
          ls -R

      - name: Replace Placeholders in Repository File
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          MY_SECRET3: ${{ secrets.MY_SECRET3 }}
        run: |
          for VAR in $(compgen -v | grep MY_SECRET); do
            PLACEHOLDER="{{${VAR}}}"
            VALUE=${!VAR}
            echo "Replacing $PLACEHOLDER with $VALUE"
            sed -i "s|$PLACEHOLDER|$VALUE|g" home/test.txt
          done
          echo "Content of updated test.txt:"
          cat home/test.txt
        shell: bash
