name: Replace Placeholders with Secrets

on:
  push:
    paths:
      - test.txt # Trigger only if test.txt is modified

  workflow_dispatch: # Allows manual trigger for testing

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Target File
        run: |
          if [ -f "/home/temp_test/test.txt" ]; then
            echo "/home/temp_test/test.txt exists"
            ls -l /home/temp_test/test.txt
          else
            echo "/home/temp_test/test.txt does not exist. Creating it."
            mkdir -p /home/temp_test
            cp test.txt /home/temp_test/test.txt
            chmod 666 /home/temp_test/test.txt
          fi

      - name: Replace Placeholders Dynamically
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          MY_SECRET3: ${{ secrets.MY_SECRET3 }}
        run: |
          for VAR in $(compgen -v | grep MY_SECRET); do
            PLACEHOLDER="{{${VAR}}}"
            VALUE=${!VAR}
            echo "Replacing $PLACEHOLDER with $VALUE"
            sed -i "s|$PLACEHOLDER|$VALUE|g" /home/temp_test/test.txt
          done
          echo "Content of updated /home/temp_test/test.txt:"
          cat /home/temp_test/test.txt
        shell: bash
