name: Replace Placeholders with Secrets

on:
  push:
    paths:
      - test.txt1 # Trigger only when test.txt is modified
  workflow_dispatch: # Allows manual triggering

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Target File Exists and Populate It
        run: |
          mkdir -p /home/temp_test
          if [ -f "/home/temp_test/test.txt" ]; then
            echo "/home/temp_test/test.txt exists. Overwriting with repository content."
          else
            echo "/home/temp_test/test.txt does not exist. Creating it from repository content."
          fi
          if [ -f "test.txt" ]; then
            cp test.txt /home/temp_test/test.txt
            chmod 666 /home/temp_test/test.txt
          else
            echo "Repository file test.txt is missing. Exiting."
            exit 1
          fi

      - name: Replace Placeholders Dynamically
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_SECRET1: ${{ secrets.MY_SECRET1 }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          MY_SECRET3: ${{ secrets.MY_SECRET3 }}
        run: |
          for VAR in $(compgen -v | grep MY_SECRET); do
            PLACEHOLDER="{{${VAR}}}"
            VALUE=${!VAR}
            echo "Replacing $PLACEHOLDER with $VALUE"
            sed -i "s|$PLACEHOLDER|$VALUE|g" /home/temp_test/test.txt
          done
          echo "Content of updated /home/temp_test/test.txt:"
          cat /home/temp_test/test.txt
        shell: bash
