name: Replace Placeholders with Secrets

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Debug File Permissions
        run: |
          if [ -f "/home/test.txt" ]; then
            echo "/home/test.txt exists"
            ls -l /home/test.txt
          else
            echo "/home/test.txt does not exist. Creating it."
            touch /home/test.txt
            chmod 666 /home/test.txt
          fi

      - name: Replace Placeholders Dynamically
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          MY_SECRET3: ${{ secrets.MY_SECRET3 }}
        run: |
          for VAR in $(compgen -v | grep MY_SECRET); do
            PLACEHOLDER="{{${VAR}}}"
            VALUE=${!VAR}
            echo "Replacing $PLACEHOLDER with $VALUE"
            sed -i "s|$PLACEHOLDER|$VALUE|g" /home/test.txt
          done
          echo "Content of updated /home/test.txt:"
          cat /home/test.txt
        shell: bash
