name: Replace Placeholders with Secrets

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Replace Placeholders Directly in Repository File
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          MY_SECRET2: ${{ secrets.MY_SECRET2 }}
          MY_SECRET3: ${{ secrets.MY_SECRET3 }}
          # Add more secrets here as needed
        run: |
          for VAR in $(compgen -v | grep MY_SECRET); do
            VALUE=${!VAR}
            sed -i "s/{{$VAR}}/$VALUE/g" test.txt
          done
        shell: bash
